[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-8_x']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['echo "Backend only - no build step required"']

[start]
cmd = 'cd backend && node src/app.js'